import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
    fetch("http://localhost:3000/api/BandcampData")
        .then((e) => e.json())
        .then((data) => console.log(data));

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    );
};

export default Home;
