import type { NextPage } from "next";
import Head from "next/head";
import { iframesBandcampDataParser } from "../helpers/domParser/iframesBandcampDataParser";

const Sounds: NextPage = ({ arrayDataIframes }: any) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                {arrayDataIframes.map(({ srcIframe, hrefAnchor, title }: any) => (
                    <iframe
                        key={srcIframe}
                        style={{ border: "0", width: "100%", height: "42px" }}
                        src={srcIframe}
                    >
                        {title}
                    </iframe>
                ))}
            </div>
        </div>
    );
};

export default Sounds;
export async function getStaticProps() {
    const dataBandcamp = await fetch(`https://sa2-9ifwczj9r-piotrko64.vercel.app/api/bandcampData`).then(
        (e) => e.json()
    );
    console.log(dataBandcamp);
    return { props: { arrayDataIframes: iframesBandcampDataParser(dataBandcamp.iframes) } };
}
